SELECT DISTINCT
	API_NAME, 
    METHOD_NAME, 
    NULL AS EDA_QUEUE_NAME, 
    NULL AS UDG_OBJECT,
    NULL AS EVENT,
    CASE 
        WHEN API_NAME IS NOT NULL THEN 'ApplicationInterface'
        ELSE NULL
    END AS ELEMENT
FROM 
	API_METHOD_METADATA
UNION ALL
SELECT DISTINCT
	NULL, NULL, QUEUE_NAME, NULL, NULL,
    CASE 
        WHEN QUEUE_NAME IS NOT NULL THEN 'ApplicationService'
        ELSE NULL
    END AS ELEMENT
FROM 
	EDA_DESTINATIONS
UNION ALL
SELECT DISTINCT 
	NULL, NULL, NULL, REPLACE(REGEXP_REPLACE(NAME, ':[^:]+:', ':'), ':', '.'), NULL,
    CASE 
		WHEN NAME IS NOT NULL THEN 'ApplicationService'
        ELSE NULL
	END AS ELEMENT
FROM 
	udg.OBJECTS
UNION ALL
SELECT DISTINCT 
	NULL, NULL, NULL, NULL, ATTRIBUTE_2,
    CASE 
        WHEN ATTRIBUTE_2 IS NOT NULL THEN 'ApplicationEvent'
        ELSE NULL
    END AS ELEMENT
FROM 
	EDA_EVENT_ACTIONS 
WHERE TIMESTAMP >= DATE_SUB(CURDATE(), INTERVAL 3 DAY);